### ISSUE TITLE
Does it work on version 954.2q

### ISSUE THREAD

**Issue by reactgary** [ib-controller/ib-controller#57] opened 2016-01-14 14:45 UTC
I could not locate the jts.jar and total.jar in my 954.2q installation of tws
wonder if IB have some big change on its jar file which prevent ibcontroller to start?

**Comment by rlktradewright** [comment] 2016-01-14 16:20
IBController still works perfectly, but you have to tweak things a bit because starting with TWS 952, IB have changed the way TWS is packaged, and things are no longer in the folders that the IBController scripts have as default. In particular the jar files are no longer in C:\Jts, but in C:\Jts\nnn\jars where nnn is the TWS major version number.

I haven’t yet got round to making a new release of IBController that takes account of this change. Apologies for the problems this is causing you (and several; others). I will try to find time for this very soon.

Here's how to fix things.

First off, you must use the downloadable version of TWS (I think IB now call it the ‘Offline’ version on their website): IBController has never supported the auto-updating version of TWS.

Next change the relevant lines in your IBControllerStart.bat file as follows:

set TWSDIR=C:\Jts\954\jars

set TWSCP=jts.jar;total.jar

set JAVAOPTS=-Dsun.java2d.noddraw=true -Dswing.boldMetal=false -Dsun.locale.formatasdefault=true -Xmx1024M

Then it should work properly.

**Comment by shiroh** [comment] 2016-01-14 17:11
I faced same problem days back, and it costs me hours to fix. 
Just download the offline tws , not offline tws latest, which version is 952 to have the right jar files.
https://www.interactivebrokers.com/en/index.php?f=16045&ns=T

**Comment by rlktradewright** [comment] 2016-01-14 20:06
@shiroh , the question related to TWS 954.2q, not TWS 952. So he needs to download offline latest.

**Comment by rlktradewright** [comment] 2016-02-22 17:18
The problems caused by IB changing the locations of files are resolved by using IBController v3.0.0 or later.

**Closed by rlktradewright** 2016-02-22 17:18 UTC
