### ISSUE TITLE
IBControllerStart.sh not working unless you provide username and password in .sh file

### ISSUE THREAD

**Issue by SamoPP** [ib-controller/ib-controller#16] opened 2015-02-15 12:23 UTC
HI,

Thanks for this great utility. I tried to set it up this morning, but failed.

To me it looks that on Ubuntu the only way to make this work is provide Id nad password "hardcoded" in IBControllerStart.sh. If you leave them blank they are not red from .ini file and the application does not start. This is the error message:

"IBController: 2 arguments passed, but args[0] is not 'encrypt'. quitting..."

Apllication starts fine if I provide username and password in IBControllerStart.sh file...

**Comment by rlktradewright** [comment] 2015-02-16 14:38
Well, I just set it up on a fresh Ubuntu VM and it works just fine with the user id and password in the .ini file.

The error message you're getting perhaps gives a hint. It says you passed 2 arguments to the java command, but there should be either just one (the .ini path and filename) or three (the .ini file, the user id and the password). Two arguments is only allowed when 'encrypting' the password (as the error message states).

So you must have set either TWSUSERID or TWSPASSWORD (but not both) to something non-blank, whereas they should both be blank.

By the way, I noticed that the downloaded .sh files contain Windows line-endings (\r\n), rather than Unix (\n), which causes problems with bash. You've presumably already discovered this and corrected it, but I'll try to remember to correct it in the next release.

**Comment by SamoPP** [comment] 2015-02-16 21:01
Thank you for your answer.

Let me give you detailed description what goes on.

This is my IBControllerStartLive.sh when at least I somehow managed to get TWS started. When started a dialog box appears asking for user id and password (so it is not read from .ini file)

#!/bin/bash

#   If your TWS user id and password are not included in the IBController 
#   configuration file, set them here (do not encrypt the password):

TWSUSERID=
TWSPASSWORD=


#   The folder containing the IBController files:

IBCDIR=/opt/IBController


#   The location and filename of the IBController configuration file. This file should
#   be in a folder in your personal filestore, so that other users of yur computer can't
#   access it. This folder and its contents should also be encrypted so that even users
#   with administrator privileges can't see the contents:

IBCINI=/home/myusername/IBController/IBControllerLive.ini


#   The folder where TWS is installed:

TWSDIR=/opt/IBJts/IBJts


#   The classpath for TWS. The value below is correct for version
#   942 (you can verify which version of TWS you are using by going
#   to the Help | About Trader Workstation menu in TWS).
#
#   For other versions of TWS, the information needed may change.
#   You can find the required information in the UNIX/MacOsX download instructions
#   for TWS on the IB website, which includes a sample command to start TWS.
#
#   You must include everything after "-cp " up to the 
#   first subsequent space character:

# Setting classpath like this does not work for me
TWSCP=jts.jar:total.2013.jar


#   Other Java VM options for TWS. You can find this information in the 
#   UNIX/MacosX download instructions for TWS on the IB website. (Note that
#   jclient.LoginFrame is NOT part of the Java options, nor is anything 
#   that comes after it, so don't include that here):

# This is not working for me
JAVAOPTS=-Xmx1G -XX:MaxPermSize=256M

# pushd is not recognized on my Ubuntu so I revert to full paths
#pushd $TWSDIR
java -cp  /opt/IBJts/IBJts/jts.jar:/opt/IBJts/IBJts/total.2013.jar:/opt/IBController/IBController.jar -Xmx1G -XX:MaxPermSize=512M ibcontroller.IBController /home/myusername/IBController/IBControllerLive.ini  $TWSUSERID $TWSPASSWORD
#popd

This is the terminal output when I use the file as above:
myusername@myusernameVB:~/Desktop$ sh IBControllerStartLive.sh
: not foundrStartLive.sh: 2: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 5: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 8: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 9: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 11: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 13: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 14: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 19: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 21: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 22: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 24: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 26: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 27: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 38: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 40: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 41: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 46: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 48: IBControllerStartLive.sh: 
System Properties
------------------------------------------------------------
java.runtime.name = Java(TM) SE Runtime Environment
sun.boot.library.path = /usr/lib/jvm/jdk1.7.0_25/jre/lib/amd64
java.vm.version = 23.25-b01
java.vm.vendor = Oracle Corporation
java.vendor.url = http://java.oracle.com/
path.separator = :
java.vm.name = Java HotSpot(TM) 64-Bit Server VM
file.encoding.pkg = sun.io
user.country = US
sun.java.launcher = SUN_STANDARD
sun.os.patch.level = unknown
java.vm.specification.name = Java Virtual Machine Specification
user.dir = /home/myusername/Desktop
java.runtime.version = 1.7.0_25-b15
java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
java.endorsed.dirs = /usr/lib/jvm/jdk1.7.0_25/jre/lib/endorsed
os.arch = amd64
java.io.tmpdir = /tmp
line.separator = 

java.vm.specification.vendor = Oracle Corporation
os.name = Linux
sun.jnu.encoding = UTF-8
java.library.path = /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
java.specification.name = Java Platform API Specification
java.class.version = 51.0
sun.management.compiler = HotSpot 64-Bit Tiered Compilers
os.version = 3.13.0-45-generic
user.home = /home/myusername
user.timezone = America/New_York
java.awt.printerjob = sun.print.PSPrinterJob
file.encoding = UTF-8
java.specification.version = 1.7
java.class.path = /opt/IBJts/IBJts/jts.jar:/opt/IBJts/IBJts/total.2013.jar:/opt/IBController/IBController.jar
user.name = myusername
java.vm.specification.version = 1.7
 un.java.command = ibcontroller.IBController /home/myusername/IBController/IBControllerLive.ini 
java.home = /usr/lib/jvm/jdk1.7.0_25/jre
sun.arch.data.model = 64
user.language = en
java.specification.vendor = Oracle Corporation
awt.toolkit = sun.awt.X11.XToolkit
java.vm.info = mixed mode
java.version = 1.7.0_25
java.ext.dirs = /usr/lib/jvm/jdk1.7.0_25/jre/lib/ext:/usr/java/packages/lib/ext
sun.boot.class.path = /usr/lib/jvm/jdk1.7.0_25/jre/lib/resources.jar:/usr/lib/jvm/jdk1.7.0_25/jre/lib/rt.jar:/usr/lib/jvm/jdk1.7.0_25/jre/lib/sunrsasign.jar:/usr/lib/jvm/jdk1.7.0_25/jre/lib/jsse.jar:/usr/lib/jvm/jdk1.7.0_25/jre/lib/jce.jar:/usr/lib/jvm/jdk1.7.0_25/jre/lib/charsets.jar:/usr/lib/jvm/jdk1.7.0_25/jre/lib/jfr.jar:/usr/lib/jvm/jdk1.7.0_25/jre/classes
java.vendor = Oracle Corporation
file.separator = /
java.vendor.url.bug = http://bugreport.sun.com/bugreport/
sun.io.unicode.encoding = UnicodeLittle
sun.cpu.endian = little
sun.desktop = gnome
sun.cpu.isalist = 
------------------------------------------------------------
15:39:45:010 IBController: ini file is /home/myusername/IBController/IBControllerLive.ini
15:39:45:019 IBController: TWS will be shut down at 2015/02/21 06:00
15:39:45:025 IBController: IBControllerServer is started.
15:39:45:118 IBController: IBControllerServer listening on address: myusernameVB/127.0.1.1 port: 7462
15:39:45:224 IBController: Invalid number "" for property "ForceTwsApiPort"
15:39:46:699 JTS-Main: dayInit: new values: dayOfTheWeek: 2 (Mon), YYYYMMofToday: 201502, YYYYMMDDofToday: 20150216
15:39:47:084 JTS-Main: LOCALE: needToUpdate  dest=/home/myusername/Jts/locales.jar  sourceMod=2014-08-07 14:45:00  destMod=2014-08-07 14:45:00  sourceSize=61859  destSize=61859  conditions=[NEWER_REMOTE, LOCAL_IN_FUTURE, SIZE_DIFFERS]  download=false
15:39:48:771 JTS-Main: Build 947.2o, Nov 5, 2014 4:06:03 PM

Now, let's look if I follow your recommendation and omit userid and password (which are set to blank, BTW):

#!/bin/bash

#   If your TWS user id and password are not included in the IBController 
#   configuration file, set them here (do not encrypt the password):

TWSUSERID=
TWSPASSWORD=


#   The folder containing the IBController files:

IBCDIR=/opt/IBController


#   The location and filename of the IBController configuration file. This file should
#   be in a folder in your personal filestore, so that other users of yur computer can't
#   access it. This folder and its contents should also be encrypted so that even users
#   with administrator privileges can't see the contents:

IBCINI=/home/myusername/IBController/IBControllerLive.ini


#   The folder where TWS is installed:

TWSDIR=/opt/IBJts/IBJts


#   The classpath for TWS. The value below is correct for version
#   942 (you can verify which version of TWS you are using by going
#   to the Help | About Trader Workstation menu in TWS).
#
#   For other versions of TWS, the information needed may change.
#   You can find the required information in the UNIX/MacOsX download instructions
#   for TWS on the IB website, which includes a sample command to start TWS.
#
#   You must include everything after "-cp " up to the 
#   first subsequent space character:

# Setting classpath like this does not work for me
TWSCP=jts.jar:total.2013.jar


#   Other Java VM options for TWS. You can find this information in the 
#   UNIX/MacosX download instructions for TWS on the IB website. (Note that
#   jclient.LoginFrame is NOT part of the Java options, nor is anything 
#   that comes after it, so don't include that here):

# This is not working for me
JAVAOPTS=-Xmx1G -XX:MaxPermSize=256M

# pushd is not recognized on my Ubuntu so I revert to full paths
#pushd $TWSDIR
java -cp  /opt/IBJts/IBJts/jts.jar:/opt/IBJts/IBJts/total.2013.jar:/opt/IBController/IBController.jar -Xmx1G -XX:MaxPermSize=512M ibcontroller.IBController /home/myusername/IBController/IBControllerLive.ini
#popd

And if I run this in terminal:
myusername@myusernameVB:~/Desktop$ sh IBControllerStartLive.sh
: not foundrStartLive.sh: 2: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 5: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 8: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 9: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 11: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 13: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 14: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 19: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 21: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 22: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 24: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 26: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 27: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 38: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 40: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 41: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 46: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 48: IBControllerStartLive.sh: 
System Properties
------------------------------------------------------------
java.runtime.name = Java(TM) SE Runtime Environment
sun.boot.library.path = /usr/lib/jvm/jdk1.7.0_25/jre/lib/amd64
java.vm.version = 23.25-b01
java.vm.vendor = Oracle Corporation
java.vendor.url = http://java.oracle.com/
path.separator = :
java.vm.name = Java HotSpot(TM) 64-Bit Server VM
file.encoding.pkg = sun.io
user.country = US
sun.java.launcher = SUN_STANDARD
sun.os.patch.level = unknown
java.vm.specification.name = Java Virtual Machine Specification
user.dir = /home/myusername/Desktop
java.runtime.version = 1.7.0_25-b15
java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
java.endorsed.dirs = /usr/lib/jvm/jdk1.7.0_25/jre/lib/endorsed
os.arch = amd64
java.io.tmpdir = /tmp
line.separator = 

java.vm.specification.vendor = Oracle Corporation
os.name = Linux
sun.jnu.encoding = UTF-8
java.library.path = /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
java.specification.name = Java Platform API Specification
java.class.version = 51.0
sun.management.compiler = HotSpot 64-Bit Tiered Compilers
os.version = 3.13.0-45-generic
user.home = /home/myusername
user.timezone = America/New_York
java.awt.printerjob = sun.print.PSPrinterJob
file.encoding = UTF-8
java.specification.version = 1.7
java.class.path = /opt/IBJts/IBJts/jts.jar:/opt/IBJts/IBJts/total.2013.jar:/opt/IBController/IBController.jar
user.name = myusername
java.vm.specification.version = 1.7
sun.java.command = ibcontroller.IBController /home/myusername/IBController/IBControllerLive.ini
java.home = /usr/lib/jvm/jdk1.7.0_25/jre
sun.arch.data.model = 64
user.language = en
java.specification.vendor = Oracle Corporation
awt.toolkit = sun.awt.X11.XToolkit
java.vm.info = mixed mode
java.version = 1.7.0_25
java.ext.dirs = /usr/lib/jvm/jdk1.7.0_25/jre/lib/ext:/usr/java/packages/lib/ext
sun.boot.class.path = /usr/lib/jvm/jdk1.7.0_25/jre/lib/resources.jar:/usr/lib/jvm/jdk1.7.0_25/jre/lib/rt.jar:/usr/lib/jvm/jdk1.7.0_25/jre/lib/sunrsasign.jar:/usr/lib/jvm/jdk1.7.0_25/jre/lib/jsse.jar:/usr/lib/jvm/jdk1.7.0_25/jre/lib/jce.jar:/usr/lib/jvm/jdk1.7.0_25/jre/lib/charsets.jar:/usr/lib/jvm/jdk1.7.0_25/jre/lib/jfr.jar:/usr/lib/jvm/jdk1.7.0_25/jre/classes
java.vendor = Oracle Corporation
file.separator = /
java.vendor.url.bug = http://bugreport.sun.com/bugreport/
sun.io.unicode.encoding = UnicodeLittle
sun.cpu.endian = little
sun.desktop = gnome
sun.cpu.isalist = 
------------------------------------------------------------
" either does not exist, or is a directory.  quitting...BControllerLive.ini
: not foundrStartLive.sh: 52: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 53: IBControllerStartLive.sh: 
: not foundrStartLive.sh: 54: IBControllerStartLive.sh: 
myusername@myusernameVB:~/Desktop$ 


And nothing happens. No dialog box, nothing...


I belive you it works if everything is set as intended (by default). But it might fail if non default paths etc. are being employed. But, my configurration is not the same as default. TWS is installed in /opt but not in /opt/IBJts but in /opt/IBJts/IBJts. My password in .ini file  is encrypted and .ini file name is different again /home/kilometrics/IBController/IBControllerLive.ini . Folder /home/kilometrics/IBController/ is encrypted...

Any ideas why this is not working? What am I doing wrong here? Thanks.

**Comment by rlktradewright** [comment] 2015-02-17 00:18
In my previous response I pointed out the issue with the incorrect line endings in the .sh files in the download. I'm concerned about all the strange error messages you get like

 : not foundrStartLive.sh: 2: IBControllerStartLive.sh:  

and I suspect that at least some of your line endings are incorrect, and that this is the source of your problems. Here's an easy way to make sure all lines have the Unix ending.

Please start again with the downloaded versions of the files, because you've made a lot of unnecessary modifications to them (eg popd DOES work on Ubuntu, and setting the classpath from an environment variable DOES work perfectly). Follow this procedure for each of IBControllerStart.sh, IBControllerGatewayStart.sh and IBController.ini.

In the Files program, navigate to your IBController directory. 

Create a new empty file by right clicking in the right hand pane and selecting New Document > Empty Document, and give it any filename (eg qaz).

Right click on the new file and select Open With gedit.

Right click on IBControllerStart.sh and select Open With gedit.

In gedit, select all the text in IBControllerStart.sh using Ctrl-A, then paste it into the new file using Ctrl-V. Save the new file. The new file will automatically have the correct line endings.

Rename the original IBControllerStart.sh to IBControllerStart.old, and rename the new file to IBControllerStart.sh.

You can now change any paths as required, then run the new IBControllerStart.sh and everything should be fine.

I can absolutely guarantee that if you've set things up properly, there is no problem with having your user id and password in the .ini file.

By the way, I should also add that the line that reads 

JAVAOPTS=-Xmx1G -XX:MaxPermSize=256M

should actually be 

JAVAOPTS='-Xmx1G -XX:MaxPermSize=256M'

This will be corrected in the next release.

**Comment by benalexau** [comment] 2015-02-18 01:56
Just noting the Unix line endings and quote-based escaping were fixed in Pull Request #17. I'll close this ticket given it could not be reproduced and the two identified enhancements have been completed already in PR #17.

**Closed by benalexau** 2015-02-18 01:56 UTC
