### ISSUE TITLE
java.lang.IllegalStateException in TwsListener.java

### ISSUE THREAD

**Issue by verona-rupes** [ib-controller/ib-controller#18] opened 2015-02-18 09:28 UTC
I'm running ibcontroller.IBGatewayController on Java 1.7.0_76. it throws this exception . Comments on getMainWindow read "Calling this method from the Swing event dispatch thread results in an IllegalStateException being thrown."  How do i avoid this exception. Appreciate your help!!

03:56:35:238 IBController: Found Gateway main window
03:56:35:240 AWT-EventQueue-0: Error
java.lang.IllegalStateException
	at ibcontroller.TwsListener.getMainWindow(TwsListener.java:216)
	at ibcontroller.TwsListener.getMainWindow(TwsListener.java:260)
	at ibcontroller.GatewayMainWindowFrameHandler.handleWindow(GatewayMainWindowFrameHandler.java:38)
	at ibcontroller.TwsListener.eventDispatched(TwsListener.java:81)
	at java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Toolkit.java:2444)
	at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2335)
	at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2335)
	at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2335)
	at java.awt.Toolkit.notifyAWTEventListeners(Toolkit.java:2294)
	at java.awt.Component.dispatchEventImpl(Component.java:4768)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:740)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:699)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:713)
	at java.awt.EventQueue$4.run(EventQueue.java:711)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:710)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by rlktradewright** [comment] 2015-02-18 18:25
Sorry, this is a bug! It's caused by setting MinimizeMainWindow=yes in IBController.ini.

I'll be issuing a new release of IBController within the next day or so, and I'll include a fix then.
In the meantime, just ignore the error message or set MinimizeMainWindow=no.

**Comment by benalexau** [comment] 2015-02-19 23:42
Resolved in pull request #17.

**Closed by benalexau** 2015-02-19 23:42 UTC
Labels: bug
