### ISSUE TITLE
Using with docker

### ISSUE THREAD

**Issue by hestinr12** [ib-controller/ib-controller#32] opened 2015-07-10 17:50 UTC
Struggling trying to get this thing propped up in a docker container. Followed the IBGo testserver, but no luck.

tws_gateway is a successfully built object from a clone of the [this](https://github.com/gofinance/ib/tree/master/testserver).

`docker run -P username/tws_gateway`

I then copy the `boot2docker ip` and the port listed under `docker ps` for the container built from the tws_gateway image. I tried modifying the local ip used in the testserver scripts to reference `0.0.0.0` and injected the latest version of the `unixmacosx.jar` standalone from IB itself (953 I think?). I also tried editing the user account to use the `edemo` (individual) vs the provided `fdemo` (advisor account).

I then try to run my automated trading python script from the host machine (read: not from a docker container) and it fails to connect with the error: 

`<error id=-1, errorCode=502, errorMsg=Couldn't connect to TWS.  Confirm that "Enable ActiveX and Socket Clients" is enabled on the TWS "Configure->API" menu.>`

My goal in running the script locally was to simulate running the gateway on a standalone server so that I could set up an automated trading system in a cloud setup. Any help for getting this set up?

**Comment by uwe** [comment] 2015-07-10 20:51
Did you add your host IP (the VirtualBox IP) to allow API connections? I can see the IP when I type /sbin/ifconfig and look for vboxnet0. It has to be the same sub net as boot2docker IP.

**Comment by rlktradewright** [comment] 2015-07-16 10:36
@hestinr12 are you still having a problem with this? I'm very conscious that you haven't had much of a response to your query, and I'm not in a position to help as docker is way off my horizon at present.

What I would say is that the error message you quoted looks as though it has come from TWS, and maybe it means exactly what it says. If that's the case, then IBController has in fact started itself and TWS successfully, which means this issue isn't really relevant.

So if all is now ok, can you please close the issue. Thanks.

**Comment by rstms** [comment] 2015-10-07 21:38
In the latest version (952) IB changed TWS so that it always uses default configuration upon login to the 'edemo' account.   I haven't tested with the fdemo account.   Since the default setting for "Enable ActiveX and Socket Clients" is disabled, TWS isn't listening.  I use a scripted IBController->TWS environment with the edemo account in my regression tests.  To get this working with the latest TWS release, I've forked and  patched to support auto-config of API settings when running with the edemo account.   @rlktradewright, would you consider a pull request with these changes?  (They are all controlled by INI file settings which default to disabled.)

**Comment by rlktradewright** [comment] 2015-10-08 11:58
@rstms if you don't mind, could you please raise a new issue specifically for this, rather than having it buried under an issue whose title talks about Docker (even if the underlying problem is similar). In any case I won't be in a position to respond further today.

**Comment by rstms** [comment] 2015-10-08 15:11
Done: Issue #42

**Closed** 2015-10-09 09:35 UTC
