### ISSUE TITLE
Recent change to TWS prevents scripted use of API with edemo account

### ISSUE THREAD

**Issue by rstms** [ib-controller/ib-controller#42] opened 2015-10-08 15:01 UTC
In the latest version (952) IB changed TWS so that it always uses default configuration upon login to the 'edemo' account. Since the default setting for "Enable ActiveX and Socket Clients" is disabled, TWS isn't listening. I use a scripted IBController->TWS environment with the edemo account in my regression tests. To get this working with the latest TWS release, I've forked and patched to support auto-config of API settings when running with the edemo account. @rlktradewright, would you consider a pull request with these changes? (They are all controlled by INI file settings which default to disabled.)

From the patched IBController.ini:
```
# ForceTwsApiEnable may be set to 'enable' 'disable' or 'manual' 
# to configure the "Enable ActiveX and Socket API Clients" setting
# 'enable' - set the "ActiveX and Socket Client" checkbox
# 'disable' - clear the "ActiveX and Socket Client" checkbox
# 'manual' (the default) - don't modify; use the TWS saved setting

#ForceTwsApiEnable=enable


# ForceTwsApiReadOnly may be set to 'enable' 'disable' or 'manual' 
# to configure the "Read-Only API" setting
# 'enable' - set the "Read-Only API" checkbox
# 'disable' - clear the "Read-Only API" checkbox
# 'manual' (the default) - don't modify; use the TWS saved setting

#ForceTwsApiReadOnly=disable


# ForceTwsApiBypassPrecautions may be set to 'enable' 'disable' or 'manual' 
# to configure the "Bypass Order Precautions for API Orders" setting
# 'enable' - set the checkbox
# 'disable' - clear the checkbox
# 'manual' (the default) - don't modify; use the TWS saved setting

#ForceTwsApiBypassPrecautions=disable

# DemoApiEnable may be set to 'enable' to configure API connections
# using the edemo/demouser account.
# Recent versions of TWS initialize to default configuration 
# settings upon login to the demo account.  To allow use of the
# API with the edemo account for automated or scripted testing,
# this setting may be set to 'enable'
# If the setting is anything else or not set, the default is no action.
# 'enable' - autoconfigure edemo API 
# anything else: no actions

#DemoApiEnable=enable
```

**Comment by rlktradewright** [comment] 2015-10-09 10:31
You've probably picked up from what I've written elsewhere that I'm very reluctant to turn IBController into a TWS auto-configuration tool. IBController's main purpose has always been to automate things that otherwise make life difficult for people wanting to run automated systems. In general, the idea has been that the user is responsible for manually configuring TWS to suit their requirements (and the number of configuration options in TWS has increased very significantly over the years), and IBController does the things that would otherwise require them to be sitting watching TWS.

It doesn't help when IB themselves make changes that are not compatible with the previous version: for example introducing the Read-only API and defaulting it to True. This of course forces nearly every TWS API user to adjust their settings. But for live or paper-trading accounts it's not really that much of a problem, because the adjustment only needs to be made once, and the user really should have done this in their basic testing of the new version way before getting close to any live auto-trading system.

However, as you point out, the situation is now different with the demo system, as IB set all the configuration options to their defaults on every login. My understanding is that this is because IB really want people to sign up for proper accounts, rather than 'playing' with the demo system indefinitely, so they make it rather irritating to use. I think we need to have a certain sensitivity to IB's wishes, and not simply steamroller them just because we can.

So my question to you is: why do you use a demo account for your regression testing rather than a paper-trading account?

If there's a valid reason why you have to use a demo account, then there are three options:

1. You continue to run your own private version of IBController, and periodically pull from the main repository to keep things up -to-date.

2. We apply your pull request to the main repository so that everyone can use it.

3. If we decide to implement the plugin facility outlined in #44, you do this enhancement via a plugin, which would allow others to use it if they wished without affecting the 'official' IBController source code.

Options 1 and 3 have the advantage of not subjecting IBController (me in particular!) to potential criticism from IB for stomping on their policy of making the demo system pretty much useless for anything other than its intended purpose.

Option 2 doesn't appeal to me, though I'm not ruling it out: I'm always open to persuasion if you can make a good enough case.

**Comment by rlktradewright** [comment] 2015-11-19 10:34
In view of the lack of further feedback on this issue, I'm closing it.

**Closed by rlktradewright** 2015-11-19 10:34 UTC
