### ISSUE TITLE
Logging in to demo indefinitely

### ISSUE THREAD

**Issue by dnevado** [ib-controller/ib-controller#161] opened 2017-09-27 18:05 UTC
[ibcontroller.log](https://github.com/ib-controller/ib-controller/files/1338244/ibcontroller.log)
Hi guys,

Thanks for that great project. Once I decided to provide full automation, I found some issues with login into offline TWS 967 in linux with ibcontroller.

My instance is a AWS Ubuntu 16 LTS with all requirements installed. If I launch manually via script, I can log in TWS with edemo user.  However. I a launch through ibcontrolller script to autocomplete fields, TWS kees logging indefinitely.

Any suggestion?.

I have attached both log and screenshot.

Thanks in advance
![ibcontroller1](https://user-images.githubusercontent.com/6552353/30929587-3a01c896-a3bf-11e7-95e4-2d1a7b563685.png)

**Comment by rlktradewright** [comment] 2017-09-27 23:36
I think you just need to be patient. At times, logging in to TWS can take quite some time, and it looks like you just haven’t waited long enough.

However I have to admit that I haven’t checked out TWS 967 yet, so I’d better do that just to make sure there isn’t some real issue here (but I imagine if there were, someone else would have confirmed it by now).

Can I just make a couple of suggestions:

1.	Please don’t post the same question both here and to the IBController User Group, as it just means someone (often me) has to reply twice. Use one or the other. The same people watch both so there’s no advantage to double-posting. Github is probably best suited to reporting bugs and making enhancement requests. The User Group is best for  general issues, requests for advice or guidance and so on.

2.	Please don’t just edit out the bit of the IBController log that you think might be useful: everything in the log is there for a reason and can be invaluable in diagnosing problems. If there are multiple IBController runs in the log file, by all means edit out all but the relevant run, but keep the whole of that run.

Richard

**Comment by dnevado** [comment] 2017-09-28 12:47
Thanks, I´ll take in consideration how to open a issue.
None of the attempts were successful, thats weird, just few seconds ago, entering fields manually work correctly, so, I guess  if it could be a auth problem from IBController.
David 

    El Jueves 28 de septiembre de 2017 1:36, Richard L King <notifications@github.com> escribió:
 

 I think you just need to be patient. At times, logging in to TWS can take quite some time, and it looks like you just haven’t waited long enough.However I have to admit that I haven’t checked out TWS 967 yet, so I’d better do that just to make sure there isn’t some real issue here (but I imagine if there were, someone else would have confirmed it by now).Can I just make a couple of suggestions:   
   - Please don’t post the same question both here and to the IBController User Group, as it just means someone (often me) has to reply twice. Use one or the other. The same people watch both so there’s no advantage to double-posting. Github is probably best suited to reporting bugs and making enhancement requests. The User Group is best for general issues, requests for advice or guidance and so on.
   - Please don’t just edit out the bit of the IBController log that you think might be useful: everything in the log is there for a reason and can be invaluable in diagnosing problems. If there are multiple IBController runs in the log file, by all means edit out all but the relevant run, but keep the whole of that run.
Richard—

**Comment by rlktradewright** [comment] 2017-09-28 23:41
I don't understand what you're saying. IBController isn't involved in authentication, except that it puts your username and password in the appropriate fields in the login dialog and the clicks the Login button. The screenshot you included in your first post is exactly what I expect to see when IBController has clicked the Login button and TWS is actually in the process of logging in: at that point, IBController is doing nothing whatsoever.

If TWS still won't start properly under IBController, then please attach the full IBController log file to your reply. You can remove all but the latest run from the log file. Actually the best thing to do is to delete the log file, then run IBController again, then just attach the new log file to your reply.

**Comment by rlktradewright** [comment] 2017-10-07 18:02
@dnevado 

Are you still having problems with this?

If not, please close the issue.

**Comment by rlktradewright** [comment] 2017-10-10 19:29
I'll close this due to lack of response from the originator.

**Closed by rlktradewright** 2017-10-10 19:29 UTC
