### ISSUE TITLE
unknown problem

### ISSUE THREAD

**Issue by Speedmaker** [ib-controller/ib-controller#50] opened 2015-11-24 19:22 UTC
hello 
after uppdating java and using the latest and than the stable one i get the whole time the same error.. 

![image](https://cloud.githubusercontent.com/assets/16005157/11377910/c56bdadc-92e8-11e5-85b8-aef3b9f7c2c4.png)

may sombody have the same issue ? 

best regards

**Comment by rlktradewright** [comment] 2015-11-24 20:06
It looks like jts.jar isn't actually in C:\Jts.

**Comment by Speedmaker** [comment] 2015-11-24 20:11
no isnt ,,, its on 

C:\Jts\952\jars

the install dir from TWS

**Comment by Speedmaker** [comment] 2015-11-24 20:30
i copyed now those 2 files into the c:\jts 

now there are differnt errors ,, 



![image](https://cloud.githubusercontent.com/assets/16005157/11379767/783a16f2-92f2-11e5-93fe-5874142c6f05.png)

![image](https://cloud.githubusercontent.com/assets/16005157/11379778/878e4d94-92f2-11e5-82d9-b704857c7dc4.png)


some idea ?

**Comment by rlktradewright** [comment] 2015-11-24 21:05
You haven't followed the instructions in IBControllerStart.bat. 

    ::   The folder where TWS is installed:

    set TWSDIR=C:\Jts\

Don't move jts.jar from its installation directory. Just set TWSDIR= properly.

**Comment by Speedmaker** [comment] 2015-11-24 21:21
same again

![image](https://cloud.githubusercontent.com/assets/16005157/11380962/8b216048-92f9-11e5-8d9c-f97438aae548.png)

![image](https://cloud.githubusercontent.com/assets/16005157/11380982/9a09d0cc-92f9-11e5-909d-34216e15de95.png)

![image](https://cloud.githubusercontent.com/assets/16005157/11380985/9f554192-92f9-11e5-970c-c8087b522640.png)


im confused

**Comment by Speedmaker** [comment] 2015-11-24 21:25
doesnt also matter which path ,, 

![image](https://cloud.githubusercontent.com/assets/16005157/11381083/48d04b18-92fa-11e5-9b70-110df023d7a4.png)

**Comment by rlktradewright** [comment] 2015-11-24 22:31
Earlier on you said jts.jar was in C:\Jts\952\jars

So why have you got:

`set TWSDIR=C:\Jts\954`

It really is very very simple. 

For example, if you installed TWS in C:\Jts\952\jars then you need to have

`set TWSDIR=C:\Jts\952\jars`

As another example, if you installed TWS in G:\Ib\TWS954 then you need to have 

`set TWSDIR=G:\Ib\TWS954`

Get the picture? It really cannot be any easier...

**Comment by Speedmaker** [comment] 2015-11-25 08:47
hello ...

first i understand what you mean ,,

in the meantime i tryed all out ,, but all the time the same error ,,

so i realy dont know why ,,




2015-11-24 23:31 GMT+01:00 Richard L King <notifications@github.com>:

**Comment by rlktradewright** [comment] 2015-11-25 09:41
Ok, let's do this from first principles.

1. Tell me which folder you have installed IBController in.

2. Tell me which folder you have installed TWS in. It should have a whole bunch of files in it, like this:

    ![twsdir](https://cloud.githubusercontent.com/assets/7384655/11393367/418a8a00-9357-11e5-9347-89634299ca3c.PNG)

    In particular the files jts.jar and total.2015b.jar MUST BOTH be in this folder.

    If not all these files are present, then uninstall TWS and reinstall it.

3. Now copy and paste the contents of your IBControllerStart.bat file into your reply (rather than a screenshot, so that I can see the whole contents).

**Comment by Speedmaker** [comment] 2015-11-25 11:52
after install latest TWS    it looks like this ,, 

![image](https://cloud.githubusercontent.com/assets/16005157/11396535/6e309a2a-9372-11e5-9733-d2b18358203e.png)


![image](https://cloud.githubusercontent.com/assets/16005157/11396546/891e219a-9372-11e5-8a9a-bea216d136dc.png)

not more ,, now ,, 

i have not total2015b.jar on my computer

**Comment by Speedmaker** [comment] 2015-11-25 12:29
ib controller start.bat ...



::   If your TWS user id and password are not included in the IBController 
::   configuration file, set them here (do not encrypt the password):

set TWSUSERID=
set TWSPASSWORD=


::   The folder containing the IBController files:

set IBCDIR=C:\IBController


::   The location and filename of the IBController configuration file. This file should
::   be in a folder in your personal filestore, so that other users of your computer can't
::   access it. This folder and its contents should also be encrypted so that even users
::   with administrator privileges can't see the contents. Note that you can use the HOMEPATH
::   environment variable to address the root of your personal filestore (HOMEPATH is set
::   automatically by Windows):

set IBCINI="C:\Users\User\Documents\IBController\IBController.ini"


::   The folder where TWS is installed:

set TWSDIR=C:\Jts\954\


::   The classpath for TWS. The value below is correct for version
::   952 (you can verify which version of TWS you are using by going
::   to the Help | About Trader Workstation menu in TWS).
::
::   For other versions of TWS, the information needed may be different.
::   First, look in the folder where TWS is installed (typically C:\Jts).
::   If this folder contains a file called StartTWS.bat, open the file with
::   a text editor and look at the line beginning with START. Select 
::   everything after "-cp " up to the first subsequent space character,
::   then press Ctrl-C to copy it to the clipboard, then paste it into the
::   "set TWSCP=" command below, replacing everything after the "=" character.
::
::   If the StartTWS.bat file doesn't exist, you'll need to look in  the 
::   shortcut created when you installed TWS. How to find this depends on 
::   which version of Windows you're using:
::
::   - Windows 7: right click on the start menu entry for TWS and click 
::     'Properties'. 
::
::   - Windows 8: locate the tile for TWS in the start screen (or the 
::     'all apps' screen), right click it, and select 'Open file location'
::     on the menu bar at the bottom of the screen. Then right click on the
::     highlighted entry in the File Explorer window, and click 'Properties'.
::
::   - Windows 8.1: locate the tile for TWS in the start screen (or the 
::     'all apps' screen), right click it, and select 'Open file location'
::     in the context menu. Then right click on the highlighted entry in the
::     File Explorer window, and click 'Properties'.
::
::   - Windows 10: locate the tile for TWS in the start menu (or the 
::     'all apps' list), right click it, and select 'Open file location'
::     in the context menu. Then right click on the highlighted entry in
::     the File Explorer window, and click 'Properties'.
::
::   In the field labelled 'Target', select everything after "-cp " up to the 
::   first subsequent space character, then press Ctrl-C to copy it to the 
::   clipboard, then paste it into the "set TWSCP=" command below, replacing
::   everything after the "=" character:

set TWSCP=jts.jar;total.2015b.jar


::   Other Java VM options for TWS. You can find this information in the 
::   START line in StartTWS.bat (or the shortcut created when you installed 
::   TWS if StartTWS.bat doesn't exist). Note that jclient/LoginFrame is
::   NOT part of the Java options, nor is anything that comes after it, 
::   so don't include that here):

set JAVAOPTS=-Dsun.java2d.noddraw=true -Dswing.boldMetal=false -Dsun.locale.formatasdefault=true -Xmx1024M -XX:MaxPermSize=256M


pushd %TWSDIR%

:: prevent other Java tools interfering with IBController
setlocal
set JAVA_TOOL_OPTIONS=

%SystemDrive%\ProgramData\Oracle\Java\javapath\java.exe -cp  %TWSCP%;%IBCDIR%\IBController.jar %JAVAOPTS% ibcontroller.IBController %IBCINI% %TWSUSERID% %TWSPASSWORD%
popd

**Comment by Speedmaker** [comment] 2015-11-25 12:31
i cant find the total.2015b.jar  on the web ,, ??for download ,,

**Comment by rlktradewright** [comment] 2015-11-25 13:20
Ok, I see what's happening here.

It seems that since the last time I installed TWS, which was on 6 November, IB have completely changed the packaging and the folder structure of TWS installations, so that files are no longer in the same places and it uses some new means to get Java VM options declared.

At present I don't even know whether IBController will still work with this new structure: I'll have to investigate.

The unfortunate thing is that IB have done this for both the latest version 954 and the previous so-called stable version 952, so there is no longer a version downloadable from IB's website that uses the old structures (though if the worst comes to the worst I could let you have the old installer for 952 - I always keep the installers when I download them).

I'll get onto this later today, but in the meantime I'm afraid you'll just have to start TWS manually.

**Comment by Speedmaker** [comment] 2015-11-25 13:32
😉.  Finaly .. I realy was thinking im to dumb for a instalation ....


Yess iff you ard not found a solution this old version would be good :-)

Thx

Am Mittwoch, 25. November 2015 schrieb Richard L King :

**Comment by mission2010** [comment] 2015-11-25 13:36
Hi All,

I had the same issue a few weeks ago. I resolved it the following way:

1. Copy the jar files `jts.jar` and `total.jar` from the `jar directory` to the `upper directory` where you can find `tws.exe`
2. Change set `TWSCP=jts.jar;total.2015b.jar` to set `TWSCP=jts.jar;total.jar`
3. Rename the `jar directory` to something else or delete it
4. Done

This works like a charm since the first half of November 2015. I hope this helps. However this means, that you cannot start the TWS using `tws.exe`. You will need to use `IBController` or use the old batch file.

Cheers
Konstantin

**Comment by rlktradewright** [comment] 2015-11-25 14:01
Konstantin

I was hoping that might be the case, but I didn't want to mention it until I'd had a chance to try it. You've beaten me to it!

@Speedmaker sorry if I was sounding a bit intemperate earlier on, but when you know that something 'just works' and people have trouble with it, it's too easy to resent the time spent helping them. Sadly it no longer 'just works', so I was out of order. Apologies.

**Comment by Speedmaker** [comment] 2015-11-25 14:01
after doing this comes this ,,  (ib controller start bat )

![image](https://cloud.githubusercontent.com/assets/16005157/11399023/f5362db6-9384-11e5-8cee-1cba79f124d1.png)


![image](https://cloud.githubusercontent.com/assets/16005157/11399037/05a0689c-9385-11e5-942b-441308c03875.png)


without IB controller start bat ,, and rename the jars dir ,, 

![image](https://cloud.githubusercontent.com/assets/16005157/11399087/6228ebca-9385-11e5-97fc-d56c120ef44a.png)

**Comment by mission2010** [comment] 2015-11-25 14:03
@Speedmaker:
You need to rename the `jar` files in the batch file as well. That will resolve this issue. At least it did in my case.

**Comment by Speedmaker** [comment] 2015-11-25 14:05
![image](https://cloud.githubusercontent.com/assets/16005157/11399185/e830fab4-9385-11e5-8503-8f11b685a479.png)

?
 this

**Comment by rlktradewright** [comment] 2015-11-25 14:16
@Speedmaker 
The best way to do this is to leave all the TWS files exactly as installed, then do the following in IBControllerStart.bat

    set TWSDIR=C:\Jts\952\jars
    .
    .
    .
    set TWSCP=jts.jar;total.jar

This has the advantage that you can still run the tws.exe file should you ever want to, and everything will be in the right place for the uninstaller if you ever uninstall TWS.

**Comment by Speedmaker** [comment] 2015-11-25 14:29
ok ,, done ,, but not the effect ,, i wish ,, 

![image](https://cloud.githubusercontent.com/assets/16005157/11399663/3127141c-9389-11e5-8767-8db73da51039.png)


![image](https://cloud.githubusercontent.com/assets/16005157/11399680/38063dbc-9389-11e5-9aed-8cdcecf63cdc.png)

its not closing ,,,

**Comment by rlktradewright** [comment] 2015-11-25 14:33
If you want IBController to keep TWS running, then you need to set

`IbAutoClosedown=no`

in IBController.ini.

**Comment by Speedmaker** [comment] 2015-11-25 14:36
no it was this all 12h problem ,,, 

yeahhh ,, no its working ,, 
i startet it new ,, and now its working ,, befor it startet in read only mode so it was not working ,, 

not it looks good ..

**Comment by Speedmaker** [comment] 2015-11-25 14:42
i tryed it now again ,, and no reaktion ,, . hmmm

**Comment by Speedmaker** [comment] 2015-11-25 14:50
looks good now !!  .. 
 IbAutoClosedown=no

this was it finaly ,,

**Comment by Speedmaker** [comment] 2015-11-25 15:00
thank you !!!

**Comment by ajpierce** [comment] 2015-11-28 23:44
Wanted to confirm that I got it working in Linux by first moving the JAR files to a place that IB expects them:

```
mv ~/Jts/954 /opt/IBJts
```

...followed by changing [IBControllerStart.sh](https://github.com/ib-controller/ib-controller/blob/master/resources/IBControllerStart.sh#L38) from

```
# OLD
TWSDIR=/opt/IBJts
TWSCP=jts.jar:total.2013.jar
```

to

```
# NEW
TWSDIR=/opt/IBJts/jars
TWSCP=jts.jar:total.jar
```

Hope this helps you on your journey to automated trading!

**Comment by mythryl** [comment] 2016-01-17 02:02
Would it be possible to be a bit more specific on how the TWSCP value is determined?

I've got TWS 954.2q installed and I'm not seeing anything like what is described:

pal:~/Jts> ls -l
total 1220
drwxr-xr-x 3 cynbe cynbe    4096 Jan 16 17:43 dhjegxguuj
drwxr-xr-x 2 cynbe cynbe    4096 Jan 16 17:30 jars
-rw-r--r-- 1 cynbe cynbe     287 Jan 16 17:43 jts.ini
-rw-r--r-- 1 cynbe cynbe   54311 Jan 16 17:42 launcher.Sat.txt
-rw-r--r-- 1 cynbe cynbe   61859 Aug  7  2014 locales.jar
-rw-r--r-- 1 cynbe cynbe 1030556 Jan 16 17:43 log.Sat.txt
-rwxr-xr-x 1 cynbe cynbe     180 Jan 16 17:30 Trader Workstation.desktop
-rwxr-xr-x 1 cynbe cynbe   11962 Jan  8 10:30 tws
-rw-r--r-- 1 cynbe cynbe     989 Jan 16 17:30 tws.vmoptions
-rwx------ 1 cynbe cynbe   12300 Jan  8 10:30 uninstall
-rw-r--r-- 1 cynbe cynbe   34383 Jan 16 17:43 xmlopt.dat
pal:~/Jts> ls -l jars
total 58600
-rw-r--r-- 1 cynbe cynbe 51939677 Jan  8 07:31 jts4launch.latest_1452267077000.dat
-rw-r--r-- 1 cynbe cynbe   483794 Jan  8 10:30 log4j-1.2.17.jar
-rw-r--r-- 1 cynbe cynbe  6213315 Jan  8 07:31 total.latest_1452267077000.dat
-rw-r--r-- 1 cynbe cynbe     8664 Jan  8 10:30 twslaunch-install4j.jar
-rw-r--r-- 1 cynbe cynbe  1340743 Jan  8 10:30 twslaunch.latest.jar

I cannot find any file containing the string "java -cp" which most comments seem to key on.
Setting
IBCDIR=/mythryl7/IBController/
IBCINI="/mythryl7/IBController/IBController.ini"
TWSDIR=/home/cynbe/Jts
TWSCP=jts.jar:total.jar
in /mythryl7/IBController/IBControllerStart.sh
and then running it yields
Exception in thread "main" java.lang.NoClassDefFoundError: jclient/LoginFrame
        at ibcontroller.IBController.startTws(Unknown Source)
        at ibcontroller.IBController.startTwsOrGateway(Unknown Source)
        at ibcontroller.IBController.load(Unknown Source)
        at ibcontroller.IBController.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: jclient.LoginFrame
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 4 more

Apologies if my lack of recent Java experience is causing me to overlook something obvious.

BTW, I have no particular objection to dropping back to TWS 952 if that would help, but the situation seems much the same there... :-(

FWIW, the ~/Jts/tws startup script used by the Debian panel icon/shortcut includes
...
add_class_path() {
  if [ -n "$1" ] && [ `expr "$1" : '.*\*'` -eq "0" ]; then
    local_classpath="$local_classpath${local_classpath:+:}$1"
  fi
}
...
i4j_classpath="$app_home/.install4j/i4jruntime.jar"
local_classpath=""
add_class_path "$i4j_classpath"
add_class_path "$app_home/jars/log4j-1.2.17.jar"
add_class_path "$app_home/jars/twslaunch-install4j.jar"
add_class_path "$app_home/jars/twslaunch.latest.jar"
...
$INSTALL4J_JAVA_PREFIX exec "$app_java_home/bin/java" "-splash:$app_home/.install4j/s_f4w3ip.png" -Dinstall4j.jvmDir="$app_java_home" -Dexe4j.moduleName="$prg_dir/$progname" "-DinstallDir=$prg_dir/" "-Dinstall4jType=updatable" "-Dtwslaunch.autoupdate.serviceImpl=com.ib.tws.twslaunch.install4j.Install4jAutoUpdateService" "-DupdateDownloadUrl=https://download2.interactivebrokers.com/installers/tws/latest" "-Dinstall4j.launcherId=22" "-Dinstall4j.swt=false" "$vmov_1" "$vmov_2" "$vmov_3" "$vmov_4" "$vmov_5" $INSTALL4J_ADD_VM_PARAMS -classpath "$local_classpath" com.install4j.runtime.launcher.UnixLauncher launch 5cbd629 "$prg_dir/./.install4j/tws-stderr.log" "" jclient.Launcher beta=\${installer:betaFlag} \${installer:jtsConfigDir} gdc1.ibllc.com:4000 "$@"

Should I be trying to substitute the complete $local_classpath value into TWSCP...?

TIA for any pointers!
-Cynbe

**Comment by rlktradewright** [comment] 2016-01-17 19:15
@mythryl 

Two things: first you must use the downloadable version of TWS, not the 'self-updating' one, which has never been supported by IBController. The version you want is now called the 'offline' version on IB's website. From the information you gave above, it looks like you're trying to use the self-updating one, which doesn't have the same file structures.

Second, follow what ajpierce  did in the previous post, except that you'll need to replace 954 by 942.

I will tomorrow get started on producing a new release of IBController that will take account of IB's changed installation packaging for TWS (yes, I know I should have done this ages ago, but time is always short...).

Good luck!

**Comment by mythryl** [comment] 2016-01-19 17:12
rlktradewrite:  Thank you very much for very helpful advice!  I will try out ASAP.  (Sorry for the delay in responding;  I was medically indisposed for a few days.)  

Thanks much to everyone involved in producing this very useful package!

> time is always short...

Always.  But shorter for some than for others...

**Comment by rlktradewright** [comment] 2016-01-19 18:34
Oops, in my previous post I meant 952, not 942. But expect it was clear what I meant.

Oddly enough, I've been trying to make the damn thing work on Ubuntu yesterday and today, and I'm having problems. 

TWS 952 itself runs fine from the desktop icon (ie without IBController). But when I run IBController, all correctly configured, it starts TWS, does the login (to the demo system), brings up the TWS main window, and then just hangs. There is a thread using 100% CPU, which I presume is the event dispatch thread since TWS won't respond to any user input. I have to kill the Java process to stop it.

The curious thing is that once IBController has completed the login processing (which is at least 20 seconds before TWS hangs), it shouldn't be doing anything at all, so I can't imagine how it can be preventing TWS working properly. But since TWS does work properly without IBController, it must be IBController that's causing the problem. 

Unless ...  come to think of it, IBController will of course be invoked whenever TWS displays any kind of dialog, and I notice that when it hangs, the 'informative' message from IB that this is a paper-trading system rather than a live one has not yet been displayed: so maybe IBController is trying to handle this dialog and getting itself confused somehow. 

I'll check out this theory as soon as my Ubuntu VM has finished upgrading itself from 15.04 to 15.10 ... yawn. But if anyone else has already encountered this and has any insight to offer, feel free to chip in here.

**Comment by mythryl** [comment] 2016-01-20 08:27
Yes, I assumed you meant 952 not 942.  "To err is human..."  Which is why we need things like IBController :-)

Following ajpierce's recommendations after installing tws-stable-standalone-linux-x86.sh per your recommendation and invoking IBControllerStart.sh from the directory containing jts.jar per
http://www.elitetrader.com/et/index.php?threads/tws-on-linux-what-am-i-doing-wrong.283670/
seems to have resolved all my problems on this front:  TWS starts up completely hands-off,
which means I can do it from a crontab-driven watchdog script which checks for hung/crashed TWS and restarts as necessary.

Sweet!

Again, many thanks!
-Cynbe

**Comment by mythryl** [comment] 2016-01-24 00:07
BTW, just as a little side comment, if you're going to be fiddling with the code, you might think about adding some sort of facility to write out a pid file at startup. Helpful for a watchdog process that looks for a keepalive file to stop being updated and then kills the processes and restarts them.  I always use this arrangement for critical code that has to no foolin' be up all the time come hell or high water.  (The watchdog in turn gets spawned once a minute or so by crontab and then immediately exits if the watchdog keepalive is less than (say) 15 minutes old, otherwise kills the previous watchdog by pid and takes over watchdog duties.  I've used this arrangement for decades and it has been totally reliable for me.  Even if the machine reboots for whatever reason, the system is back up automatically within minutes.)

Apparently Java has serious problems returning a pid.  :-(
I'm doing the simple Linux-specific hack
try { m_pid =Integer.parseInt( ( new File("/proc/self")).getCanonicalFile().getName() ); } catch (IOException ioexception) { m_pid = 0; }
(snarfed from a chatboard) which is fine for my application. (I'm not interested in non-Linux platforms for my personal autotrading code.)  Possibly for a portable solution you just want to wait for Java9, which rumor says will finally have a decent getPid().
Anyhow, just a thought...

**Comment by rlktradewright** [comment] 2016-01-25 12:27
Interesting idea, but not really applicable in my view. The trouble is that while IBController could easily create such a file and update it periodically, that would tell you nothing about the state of TWS. 

Once you're logged in to TWS, IBController really does nothing at all except when the user interacts with TWS (apart from things like causing TWS to save settings, or shutting down at the declared time). It has no idea what TWS is up to. If TWS freezes or goes into a loop, IBController knows nothing of it. 

So at best you'd only be testing whether IBController is still handling a periodic timer task to update the file: a deadlock or loop in TWS wouldn't prevent that..

I also personally have a rather different view of the desirability of such a mechanism. If something goes wrong with TWS while I'm running an auto-trading program, it's not clear to me that automatically restarting it is desirable. Where real money is concerned, I'm much more interested in understanding what the problem was and whether it's likely to continue causing me trouble than I am worried about missing a potential trading opportunity.

This is actually quite a significant topic, because the real question is how do you detect when something has gone wrong? People have tried all sorts of different mechanisms, but none of them are guaranteed to catch all cases. In my view, such monitoring is not the business of IBController. I would regard that as a separate project.

If you want to pursue this topic in relation to IBController, please raise a separate issue where it can be discussed.

**Comment by mythryl** [comment] 2016-01-27 18:09
It's your baby!  I've implemented this in my codebase and it is working fine, so I have no personal stake.

Just to clarify, I don't rewrite the TWS/IBController pidfile constantly, only that maintained by my ApiDemo-derived logic.  I'm interested in maintaining ticklogs with as few gaps as practical. My ApiDemo-derived logic updates its pidfile each time it logs a quote;  if no quotes are logged for five minutes during trading hours, my watchdog uses the contents of the pidfiles to kill the tws and apidemo processes and restart them.  The lack of any quotes on any of the stocks I'm logging for five minutes during trading hours is sufficient indication to me that something broke in my situation; the question of how one detects hung programs in general is, as you note, an interesting question.  Tell-me-three-times seems to be the dominant answer in some subfields at least.

So anyhow, my IBController hack just writes out its pidfile once on startup, to allow for cleanly killing the process by pid if necessary.  If you're uncomfortable with that, you should definitely not do it.  It is your baby.

As I indicated, I have my hacked version doing what I need, so I have no dog in this fight and no interest in an extended debate/discussion/flamewar/whatever on the topic.  I was just tossing an idea out for consideration.

Life is Good!
Cynbe

**Comment by mythryl** [comment] 2016-01-27 18:15
(As a side comment, root-causing bugs in TWS java code without access to the source is not something I regard as a cost-effective use of my time.  IB clearly regards their code as quite buggy, witness their insistence on ensuring that it is rebooted daily.  My experience to date also suggests the presence of quite a few design and implementation errors in the standalone IB TWS codebase.  I'm satisfied to work around these problems rather than trying to fix all IB's bugs for them. My experience is that outfits like that can anyhow introduce new bugs faster than I can clear out the old ones.)

**Closed** 2016-05-10 19:06 UTC
